name: Build

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

permissions:
  contents: read
  packages: read

jobs:
  build_apk:
    name: Gerar APK Customizado
    runs-on: ubuntu-24.04
    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Setup Android Build
        uses: ./.github/actions/setup-android-build

      - name: Compilar APK de Debug
        run: |
          bundle exec fastlane assembleDebugApks

      - name: Upload do APK nos Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Nexu5Vault-Debug-APK
          path: app/build/outputs/apk/standard/debug/*.apk
          if-no-files-found: error